In [233]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [234]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [235]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [236]:
from sklearn.model_selection import train_test_split

#split the dataframe into 80%-training and 20%-testing
data_train,data_val =train_test_split(data,test_size =0.2 ,random_state=42)

print(data_train.shape)
print(data_val.shape)

(800, 2)
(200, 2)

## Data Preprocessing

In [237]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [238]:
import re
from bs4 import BeautifulSoup, Comment

In [239]:
# Create a copy column 
data['preprocessed_text'] = data['text']

In [240]:
import warnings
from bs4 import MarkupResemblesLocatorWarning

# 1. Turn off the BeautifulSoup URL warning so it doesn't clutter your notebook
warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)

# 2. Define the helper function for complete HTML structural cleaning
def clean_html_structure(text):
    # Ensure the row is treated as a string to prevent crashes on missing data
    soup = BeautifulSoup(str(text), "html.parser")
    
    # Remove all <script> and <style> tags along with their text content
    for script_or_style in soup(["script", "style"]):
        script_or_style.decompose()
        
    # Correctly locate and extract hidden HTML comments row-by-row
    comments = soup.find_all(string=lambda t: isinstance(t, Comment))
    for comment in comments:
        comment.extract()
        
    # Extract only the clean text remaining between the tags
    return soup.get_text()

# 3. Apply the helper function to your train and validation splits separately
# This completely replaces the broken 'for i, text in enumerate...' loop block
data_train['preprocessed_text'] = data_train['text'].apply(clean_html_structure)
data_val['preprocessed_text'] = data_val['text'].apply(clean_html_structure)

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [241]:
# Remove all the special characters ---                                                                    #pattern #empty string 
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'[^\w\s]', '', str(x)))

In [242]:
# Remove Numbers
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'\d+', '', str(x)))

In [243]:
# Remove all single characters ---
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'\s+[a-zA-Z]\s+', ' ', str(x)))

In [244]:
#  Remove single characters from the start ---
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'^[a-zA-Z]\s+', ' ', str(x)))

In [245]:
#Remove prefixed 'b' ---
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'^b\s+', '', str(x)))

In [246]:
# Substitute multiple spaces with a single space ---
data['preprocessed_text'] = data['preprocessed_text'].apply(lambda x: re.sub(r'\s+', ' ', str(x)))

In [247]:
#Convert to Lowercase ---
data['preprocessed_text'] = data['preprocessed_text'].str.lower().str.strip()

## Now let's work on removing stopwords
Remove the stopwords.

In [248]:
import nltk
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [249]:
from nltk.stem import WordNetLemmatizer

#Initialize the Lemmatizer tool
lemmatizer = WordNetLemmatizer()

# fucntion to Lemmatization
def stop_and_lemmatize(text):
    # Split the row of text into individual words
    words = str(text).split()
    
    # Keep the word ONLY if it is not a stopword, and transform it to its base form
    cleaned_words = [lemmatizer.lemmatize(w) for w in words if w not in stop_words]
    
    # join the remaining filtered words back together into a single text sentence
    return " ".join(cleaned_words)

In [250]:
# Apply this function across your entire DataFrame column
data['preprocessed_text'] = data['preprocessed_text'].apply(stop_and_lemmatize)

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [251]:
from collections import Counter
import pandas as pd

In [252]:
# --- 1. Filter and count words for HAM (Normal Messages) ---

# Grab all text where the label is 0 (ham) and join it into one giant string
ham_text = " ".join(data[data['label'] == 0]['preprocessed_text'].astype(str))

# Split that giant string into individual words
ham_words = ham_text.split()

# Count the frequencies of each word
ham_word_counts = Counter(ham_words)
print(ham_word_counts)

Counter({'u': 117, 'pm': 115, 'would': 106, 'state': 103, 'president': 94, 'call': 91, 'time': 84, 'percent': 77, 'secretary': 76, 'work': 73, 'mr': 71, 'one': 65, 'american': 62, 'obama': 62, 'said': 62, 'office': 60, 'ãââ': 59, 'new': 58, 'get': 57, 'year': 57, 'enough': 55, 'also': 52, 'meeting': 52, 'country': 51, 'department': 51, 'fyi': 50, 'people': 50, 'unfavorable': 48, 'know': 47, 'back': 47, 'today': 46, 'see': 46, 'issue': 44, 'day': 44, 'want': 43, 'like': 43, 'need': 42, 'house': 42, 'last': 41, 'party': 41, 'think': 39, 'could': 39, 'government': 39, 'republican': 38, 'district': 38, 'good': 37, 'first': 37, 'say': 36, 'way': 35, 'tomorrow': 34, 'right': 34, 'two': 33, 'much': 32, 'take': 32, 'minister': 32, 'let': 31, 'may': 30, 'democrat': 30, 'talk': 30, 'china': 30, 'dont': 29, 'political': 29, 'favorable': 29, 'week': 28, 'white': 28, 'policy': 27, 'public': 27, 'make': 27, 'health': 27, 'working': 27, 'heard': 27, 'official': 27, 'woman': 27, 'agreement': 27, 'arrive': 27, 'refused': 27, 'private': 26, 'deal': 26, 'election': 26, 'depart': 26, 'room': 26, 'hrd': 26, 'bill': 25, 'message': 25, 'even': 25, 'opinion': 25, 'find': 25, 'staff': 25, 'group': 24, 'email': 24, 'go': 24, 'afghanistan': 24, 'havent': 24, 'ok': 23, 'im': 23, 'business': 23, 'job': 23, 'well': 23, 'press': 23, 'made': 23, 'pls': 23, 'military': 23, 'ambassador': 23, 'next': 23, 'cheryl': 23, 'men': 23, 'en': 23, 'send': 22, 'going': 22, 'best': 22, 'point': 22, 'voter': 22, 'economy': 22, 'put': 22, 'national': 22, 'foreign': 22, 'member': 22, 'united': 22, 'route': 22, 'afghan': 21, 'late': 21, 'might': 21, 'company': 21, 'place': 21, 'general': 21, 'shift': 21, 'security': 20, 'give': 20, 'help': 20, 'nation': 20, 'come': 20, 'month': 20, 'administration': 20, 'middle': 20, 'washington': 20, 'care': 20, 'leader': 20, 'number': 20, 'obamas': 20, 'iran': 20, 'worn': 20, 'rep': 20, 'hour': 19, 'yes': 19, 'still': 19, 'question': 19, 'including': 19, 'asked': 19, 'conference': 19, 'robinson': 19, 'heyman': 19, 'wht': 19, 'sure': 18, 'home': 18, 'plan': 18, 'center': 18, 'small': 18, 'left': 18, 'story': 18, 'told': 18, 'strong': 18, 'great': 18, 'war': 18, 'support': 18, 'dem': 18, 'ind': 18, 'hvnt': 18, 'th': 17, 'schedule': 17, 'move': 17, 'clinton': 17, 'around': 17, 'major': 17, 'look': 17, 'cut': 17, 'economic': 17, 'bush': 17, 'hope': 17, 'attack': 17, 'interest': 17, 'got': 17, 'strategic': 17, 'dkna': 17, 'november': 16, 'called': 16, 'didnt': 16, 'thing': 16, 'tell': 16, 'former': 16, 'idea': 16, 'airport': 16, 'august': 16, 'night': 16, 'effort': 15, 'since': 15, 'event': 15, 'statement': 15, 'september': 15, 'position': 15, 'given': 15, 'result': 15, 'child': 15, 'led': 15, 'action': 15, 'treaty': 15, 'global': 15, 'palau': 15, 'december': 14, 'another': 14, 'among': 14, 'without': 14, 'every': 14, 'congress': 14, 'democratic': 14, 'fact': 14, 'campaign': 14, 'thanks': 14, 'change': 14, 'end': 14, 'lead': 14, 'role': 14, 'blackberry': 14, 'long': 14, 'mark': 14, 'report': 14, 'discus': 14, 'information': 14, 'romney': 14, 'development': 14, 'iranian': 14, 'draft': 14, 'holbrooke': 14, 'residence': 14, 'barack': 14, 'letter': 14, 'york': 14, 'palin': 14, 'blk': 14, 'haiti': 13, 'huma': 13, 'october': 13, 'note': 13, 'ill': 13, 'via': 13, 'clear': 13, 'cant': 13, 'side': 13, 'speak': 13, 'set': 13, 'course': 13, 'forward': 13, 'process': 13, 'offer': 13, 'instead': 13, 'average': 13, 'january': 13, 'wanted': 13, 'threat': 13, 'jake': 13, 'pakistan': 13, 'un': 13, 'age': 13, 'degree': 13, 'huckabee': 13, 'smone': 13, 'elsevol': 13, 'wldnt': 13, 'votevol': 13, 'deuel': 13, 'jamal': 13, 'making': 12, 'leave': 12, 'soon': 12, 'news': 12, 'future': 12, 'never': 12, 'later': 12, 'conservative': 12, 'took': 12, 'trying': 12, 'vote': 12, 'better': 12, 'many': 12, 'financial': 12, 'university': 12, 'sent': 12, 'copy': 12, 'head': 12, 'comment': 12, 'morning': 12, 'full': 12, 'speech': 12, 'phone': 12, 'east': 12, 'peace': 12, 'terrorist': 12, 'nuclear': 12, 'world': 12, 'ally': 12, 'dept': 12, 'follow': 12, 'bilateral': 12, 'daily': 12, 'petraeus': 12, 'daniel': 12, 'hisfavorable': 12, 'please': 11, 'line': 11, 'hillary': 11, 'name': 11, 'israel': 11, 'already': 11, 'reach': 11, 'strategy': 11, 'kid': 11, 'candidate': 11, 'likely': 11, 'problem': 11, 'away': 11, 'million': 11, 'stand': 11, 'big': 11, 'partner': 11, 'happened': 11, 'hold': 11, 'free': 11, 'yet': 11, 'list': 11, 'opportunity': 11, 'early': 11, 'mill': 11, 'chinese': 11, 'case': 11, 'past': 11, 'check': 11, 'hague': 11, 'blair': 11, 'senior': 11, 'read': 11, 'went': 11, 'netanyahu': 11, 'fiscal': 11, 'per': 11, 'able': 11, 'taliban': 11, 'print': 10, 'trip': 10, 'thx': 10, 'thought': 10, 'according': 10, 'deficit': 10, 'ago': 10, 'situation': 10, 'far': 10, 'behind': 10, 'second': 10, 'needed': 10, 'income': 10, 'believe': 10, 'become': 10, 'independent': 10, 'mean': 10, 'senate': 10, 'thats': 10, 'june': 10, 'south': 10, 'sheet': 10, 'ask': 10, 'prime': 10, 'came': 10, 'challenge': 10, 'europe': 10, 'european': 10, 'summit': 10, 'sullivan': 10, 'april': 10, 'polish': 10, 'july': 10, 'eikenberry': 10, 'presidential': 10, 'review': 10, 'civilian': 10, 'coll': 10, 'evngl': 10, 'prot': 10, 'phil': 10, 'trend': 10, 'sep': 10, 'memo': 9, 'weekend': 9, 'abedin': 9, 'keep': 9, 'project': 9, 'afternoon': 9, 'happy': 9, 'monday': 9, 'received': 9, 'actually': 9, 'meet': 9, 'st': 9, 'nothing': 9, 'within': 9, 'high': 9, 'bank': 9, 'kind': 9, 'leadership': 9, 'start': 9, 'narrative': 9, 'tax': 9, 'part': 9, 'real': 9, 'available': 9, 'using': 9, 'highly': 9, 'whether': 9, 'term': 9, 'control': 9, 'force': 9, 'poll': 9, 'following': 9, 'feel': 9, 'oil': 9, 'chance': 9, 'law': 9, 'use': 9, 'power': 9, 'strength': 9, 'diplomat': 9, 'must': 9, 'service': 9, 'looking': 9, 'ready': 9, 'jacob': 9, 'recent': 9, 'dialogue': 9, 'address': 9, 'cameron': 9, 'north': 9, 'friday': 9, 'matter': 9, 'fm': 9, 'colombian': 9, 'agreed': 9, 'clip': 9, 'proposal': 9, 'relationship': 9, 'yr': 9, 'pol': 9, 'lib': 9, 'mod': 9, 'brnagndegree': 9, 'jul': 9, 'sleep': 9, 'bottom': 8, 'special': 8, 'building': 8, 'hand': 8, 'george': 8, 'pas': 8, 'share': 8, 'try': 8, 'done': 8, 'article': 8, 'century': 8, 'language': 8, 'several': 8, 'hard': 8, 'class': 8, 'crisis': 8, 'doesnt': 8, 'held': 8, 'family': 8, 'step': 8, 'cost': 8, 'domestic': 8, 'base': 8, 'answer': 8, 'final': 8, 'met': 8, 'saw': 8, 'benefit': 8, 'ensure': 8, 'thank': 8, 'dca': 8, 'assistant': 8, 'concern': 8, 'seems': 8, 'understand': 8, 'risk': 8, 'different': 8, 'person': 8, 'kabul': 8, 'secure': 8, 'ops': 8, 'run': 8, 'decision': 8, 'however': 8, 'shaun': 8, 'getting': 8, 'signed': 8, 'possible': 8, 'attached': 8, 'explain': 8, 'india': 8, 'representative': 8, 'top': 8, 'others': 8, 'responsibility': 8, 'always': 8, 'text': 8, 'serious': 8, 'brown': 8, 'yesterday': 8, 'outer': 8, 'doc': 8, 'approval': 8, 'accord': 8, 'reelection': 8, 'approve': 8, 'rating': 8, 'himtot': 8, 'compact': 8, 'alqaida': 8, 'marshall': 7, 'sept': 7, 'visit': 7, 'wrote': 7, 'confirmed': 7, 'along': 7, 'travel': 7, 'handling': 7, 'mentioned': 7, 'write': 7, 'currently': 7, 'immediate': 7, 'populist': 7, 'latest': 7, 'training': 7, 'swing': 7, 'across': 7, 'isnt': 7, 'tea': 7, 'truth': 7, 'market': 7, 'raise': 7, 'three': 7, 'half': 7, 'sound': 7, 'iraq': 7, 'effective': 7, 'turn': 7, 'stimulus': 7, 'street': 7, 'piece': 7, 'reform': 7, 'seen': 7, 'program': 7, 'included': 7, 'low': 7, 'wont': 7, 'key': 7, 'followed': 7, 'recently': 7, 'little': 7, 'post': 7, 'provide': 7, 'agency': 7, 'agree': 7, 'love': 7, 'importance': 7, 'wednesday': 7, 'h': 7, 'management': 7, 'add': 7, 'due': 7, 'eu': 7, 'though': 7, 'region': 7, 'continue': 7, 'human': 7, 'regional': 7, 'benghazi': 7, 'traffic': 7, 'least': 7, 'briefing': 7, 'david': 7, 'republic': 7, 'current': 7, 'friend': 7, 'taken': 7, 'authority': 7, 'russian': 7, 'almost': 7, 'interview': 7, 'demand': 7, 'sending': 7, 'laguardia': 7, 'photo': 7, 'february': 7, 'cent': 7, 'gave': 7, 'developing': 7, 'mtg': 7, 'monica': 7, 'copenhagen': 7, 'delegation': 7, 'wife': 7, 'gingrich': 7, 'whitenocoll': 7, 'mar': 7, 'nov': 7, 'movement': 7, 'lgf': 7, 'pi': 6, 'contact': 6, 'date': 6, 'bad': 6, 'develop': 6, 'john': 6, 'anger': 6, 'theyre': 6, 'belief': 6, 'association': 6, 'reagan': 6, 'virtually': 6, 'toward': 6, 'rate': 6, 'whose': 6, 'credit': 6, 'executive': 6, 'anyone': 6, 'detail': 6, 'industry': 6, 'rather': 6, 'entire': 6, 'additional': 6, 'release': 6, 'lost': 6, 'certainly': 6, 'seeing': 6, 'local': 6, 'important': 6, 'play': 6, 'approach': 6, 'denied': 6, 'diplomatic': 6, 'addition': 6, 'expected': 6, 'organization': 6, 'evening': 6, 'probably': 6, 'noon': 6, 'dinner': 6, 'college': 6, 'remark': 6, 'someone': 6, 'minute': 6, 'team': 6, 'america': 6, 'investment': 6, 'period': 6, 'complete': 6, 'apr': 6, 'sign': 6, 'allowed': 6, 'life': 6, 'statecase': 6, 'fdoc': 6, 'cdate': 6, 'produced': 6, 'select': 6, 'commsubject': 6, 'sensitive': 6, 'redaction': 6, 'foia': 6, 'successful': 6, 'union': 6, 'used': 6, 'bit': 6, 'consequence': 6, 'conversation': 6, 'close': 6, 'response': 6, 'positive': 6, 'assume': 6, 'short': 6, 'jewish': 6, 'based': 6, 'jedwabne': 6, 'whole': 6, 'delegate': 6, 'prebrief': 6, 'system': 6, 'pay': 6, 'wish': 6, 'prior': 6, 'unasur': 6, 'battle': 6, 'activity': 6, 'commitment': 6, 'obviously': 6, 'capitol': 6, 'deputy': 6, 'man': 6, 'dup': 6, 'west': 6, 'assembly': 6, 'aid': 6, 'negotiation': 6, 'brief': 6, 'update': 6, 'account': 6, 'open': 6, 'closed': 6, 'target': 6, 'ive': 6, 'sarah': 6, 'karzai': 6, 'bbc': 6, 'programme': 6, 'quinnipiac': 6, 'hvn': 6, 'terrorism': 6, 'worth': 6, 'contract': 6, 'zone': 6, 'dcfs': 6, 'order': 5, 'lauren': 5, 'access': 5, 'pmhfw': 5, 'oct': 5, 'scheduled': 5, 'updated': 5, 'tom': 5, 'either': 5, 'tuesday': 5, 'unless': 5, 'together': 5, 'road': 5, 'range': 5, 'particularly': 5, 'weve': 5, 'tested': 5, 'alternative': 5, 'remain': 5, 'there': 5, 'although': 5, 'deserve': 5, 'running': 5, 'phrase': 5, 'gop': 5, 'whats': 5, 'cause': 5, 'young': 5, 'recovery': 5, 'mention': 5, 'oval': 5, 'decade': 5, 'consider': 5, 'intervention': 5, 'measure': 5, 'stop': 5, 'act': 5, 'increasingly': 5, 'card': 5, 'receive': 5, 'insurance': 5, 'declined': 5, 'win': 5, 'cabinet': 5, 'really': 5, 'land': 5, 'supposed': 5, 'allowing': 5, 'knew': 5, 'profit': 5, 'thousand': 5, 'ofthe': 5, 'choice': 5, 'rule': 5, 'true': 5, 'school': 5, 'grateful': 5, 'personnel': 5, 'affair': 5, 'spoke': 5, 'ecuador': 5, 'ground': 5, 'id': 5, 'requested': 5, 'higher': 5, 'ny': 5, 'something': 5, 'opening': 5, 'argentina': 5, 'regarding': 5, 'justice': 5, 'philippe': 5, 'talked': 5, 'quick': 5, 'level': 5, 'prospect': 5, 'encourage': 5, 'benjamin': 5, 'waiver': 5, 'defense': 5, 'version': 5, 'asap': 5, 'tory': 5, 'shes': 5, 'directly': 5, 'fax': 5, 'checking': 5, 'rich': 5, 'info': 5, 'invite': 5, 'coming': 5, 'border': 5, 'moldova': 5, 'jew': 5, 'area': 5, 'forced': 5, 'apology': 5, 'eastern': 5, 'amount': 5, 'tonight': 5, 'lot': 5, 'allow': 5, 'honduras': 5, 'shuttle': 5, 'floor': 5, 'output': 5, 'monetary': 5, 'actual': 5, 'meant': 5, 'lower': 5, 'relatively': 5, 'happen': 5, 'establishment': 5, 'attend': 5, 'inthe': 5, 'respect': 5, 'madam': 5, 'robert': 5, 'overall': 5, 'large': 5, 'international': 5, 'camp': 5, 'fully': 5, 'missile': 5, 'weapon': 5, 'defence': 5, 'earlier': 5, 'sorry': 5, 'blame': 5, 'table': 5, 'viewed': 5, 'gaf': 5, 'buy': 5, 'everything': 5, 'saying': 5, 'ireland': 5, 'announced': 5, 'mitt': 5, 'mike': 5, 'newt': 5, 'gov': 5, 'womens': 5, 'jeff': 5, 'basis': 5, 'susan': 5, 'cnpc': 5, 'oslo': 5, 'deprivation': 5, 'hr': 5, 'convoy': 5, 'bin': 5, 'laden': 5, 'computer': 4, 'gotten': 4, 'weekly': 4, 'steinberg': 4, 'behalf': 4, 'feedback': 4, 'partb': 4, 'de': 4, 'westen': 4, 'politics': 4, 'sector': 4, 'ability': 4, 'energy': 4, 'build': 4, 'worker': 4, 'unemployment': 4, 'anything': 4, 'victory': 4, 'create': 4, 'billion': 4, 'bailouts': 4, 'remind': 4, 'hear': 4, 'refuse': 4, 'mess': 4, 'economics': 4, 'spending': 4, 'opponent': 4, 'paying': 4, 'defensive': 4, 'hadnt': 4, 'third': 4, 'solution': 4, 'produce': 4, 'predictable': 4, 'polling': 4, 'necessary': 4, 'perhaps': 4, 'negative': 4, 'pull': 4, 'wall': 4, 'legislation': 4, 'popular': 4, 'record': 4, 'despite': 4, 'margin': 4, 'sell': 4, 'option': 4, 'supported': 4, 'watch': 4, 'senator': 4, 'voting': 4, 'ever': 4, 'drop': 4, 'return': 4, 'failed': 4, 'central': 4, 'tough': 4, 'climate': 4, 'moving': 4, 'effect': 4, 'less': 4, 'bp': 4, 'disaster': 4, 'offensive': 4, 'protection': 4, 'connect': 4, 'assessment': 4, 'performance': 4, 'whitehouse': 4, 'word': 4, 'fair': 4, 'guarantee': 4, 'expect': 4, 'break': 4, 'partnership': 4, 'cell': 4, 'associated': 4, 'institute': 4, 'announcement': 4, 'africa': 4, 'mcguinness': 4, 'front': 4, 'att': 4, 'madame': 4, 'wonderful': 4, 'french': 4, 'calling': 4, 'fw': 4, 'valmorospecial': 4, 'valenzuela': 4, 'present': 4, 'interior': 4, 'subject': 4, 'kurt': 4, 'summary': 4, 'medium': 4, 'suggest': 4, 'yeah': 4, 'b': 4, 'influence': 4, 'direction': 4, 'deserves': 4, 'maintain': 4, 'lack': 4, 'freedom': 4, 'seek': 4, 'indeed': 4, 'priority': 4, 'appointment': 4, 'doubt': 4, 'council': 4, 'raised': 4, 'critic': 4, 'poland': 4, 'chief': 4, 'cooperation': 4, 'expert': 4, 'lisa': 4, 'romania': 4, 'soviet': 4, 'biggest': 4, 'transition': 4, 'troop': 4, 'settlement': 4, 'confidence': 4, 'apologise': 4, 'show': 4, 'kaminski': 4, 'massacre': 4, 'giving': 4, 'asking': 4, 'pattern': 4, 'argued': 4, 'personality': 4, 'he': 4, 'brazil': 4, 'boy': 4, 'upcoming': 4, 'brought': 4, 'collapse': 4, 'wrong': 4, 'adviser': 4, 'decline': 4, 'outcome': 4, 'congressional': 4, 'percentage': 4, 'extraordinary': 4, 'personal': 4, 'sbu': 4, 'deliver': 4, 'moment': 4, 'provides': 4, 'violence': 4, 'hemisphere': 4, 'addressed': 4, 'trafficking': 4, 'near': 4, 'anniversary': 4, 'seemed': 4, 'expressed': 4, 'theme': 4, 'failure': 4, 'black': 4, 'else': 4, 'lona': 4, 'easy': 4, 'voted': 4, 'sid': 4, 'cingular': 4, 'xpress': 4, 'mail': 4, 'jon': 4, 'preceding': 4, 'belfast': 4, 'concerned': 4, 'tip': 4, 'amh': 4, 'field': 4, 'rest': 4, 'offence': 4, 'abm': 4, 'believed': 4, 'father': 4, 'site': 4, 'closely': 4, 'davis': 4, 'etc': 4, 'society': 4, 'writing': 4, 'guardian': 4, 'suicide': 4, 'session': 4, 'gordon': 4, 'pressure': 4, 'dc': 4, 'sunday': 4, 'chemical': 4, 'march': 4, 'money': 4, 'cherie': 4, 'attachment': 4, 'virus': 4, 'marty': 4, 'joint': 4, 'ahead': 4, 'northern': 4, 'helped': 4, 'mitch': 4, 'm': 4, 'barbour': 4, 'thune': 4, 'florida': 4, 'votetot': 4, 'hisobama': 4, 'conobama': 4, 'cathobama': 4, 'elk': 4, 'himnov': 4, 'ct': 4, 'prepare': 4, 'qddr': 4, 'community': 4, 'section': 4, 'decide': 4, 'sc': 4, 'magazine': 4, 'increased': 4, 'oilfield': 4, 'azadegan': 4, 'approximately': 4, 'defined': 4, 'sleeping': 4, 'christmas': 4, 'omar': 4, 'disapprove': 4, 'attempted': 4, 'organize': 3, 'outside': 3, 'employee': 3, 'productivity': 3, 'separate': 3, 'relevant': 3, 'hrodclintonemailcomwednesday': 3, 'passing': 3, 'copying': 3, 'hrodclintonemailcommonday': 3, 'govt': 3, 'traveling': 3, 'nora': 3, 'toiv': 3, 'toivnfstategov': 3, 'emergency': 3, 'operation': 3, 'youcdm': 3, 'midterm': 3, 'brain': 3, 'created': 3, 'explosion': 3, 'avoid': 3, 'join': 3, 'damage': 3, 'plenty': 3, 'fix': 3, 'spent': 3, 'four': 3, 'enthusiasm': 3, 'beat': 3, 'summer': 3, 'eventually': 3, 'single': 3, 'partisan': 3, 'alloyed': 3, 'stock': 3, 'willing': 3, 'regulation': 3, 'accountability': 3, 'expectation': 3, 'waiting': 3, 'desperately': 3, 'initiative': 3, 'clean': 3, 'increase': 3, 'putting': 3, 'eight': 3, 'otherwise': 3, 'mental': 3, 'explanation': 3, 'trillion': 3, 'soldier': 3, 'ronald': 3, 'package': 3, 'continues': 3, 'freefall': 3, 'provision': 3, 'designed': 3, 'attacking': 3, 'thrown': 3, 'nearly': 3, 'attention': 3, 'federal': 3, 'adding': 3, 'double': 3, 'existing': 3, 'continuing': 3, 'except': 3, 'opposition': 3, 'element': 3, 'history': 3, 'debate': 3, 'evocative': 3, 'death': 3, 'popularity': 3, 'alike': 3, 'choose': 3, 'desire': 3, 'theyve': 3, 'hit': 3, 'primary': 3, 'emotion': 3, 'covered': 3, 'none': 3, 'increasing': 3, 'resolve': 3, 'exist': 3, 'vision': 3, 'coherent': 3, 'motivation': 3, 'contrast': 3, 'common': 3, 'sense': 3, 'subsidiary': 3, 'utterly': 3, 'certain': 3, 'lose': 3, 'seat': 3, 'living': 3, 'enormous': 3, 'red': 3, 'advice': 3, 'youll': 3, 'agenda': 3, 'bipartisan': 3, 'hasnt': 3, 'wed': 3, 'simply': 3, 'worry': 3, 'fall': 3, 'opposed': 3, 'corporate': 3, 'limit': 3, 'thefirst': 3, 'governance': 3, 'roadmap': 3, 'include': 3, 'rebuilding': 3, 'phd': 3, 'rodham': 3, 'announce': 3, 'gay': 3, 'notice': 3, 'medical': 3, 'provided': 3, 'informed': 3, 'lift': 3, 'shannon': 3, 'promise': 3, 'released': 3, 'guidance': 3, 'appropriate': 3, 'connection': 3, 'page': 3, 'slaughterdirector': 3, 'planningus': 3, 'responded': 3, 'amhre': 3, 'education': 3, 'anytime': 3, 'book': 3, 'annemarie': 3, 'inside': 3, 'cgi': 3, 'written': 3, 'fine': 3, 'hrodclintonemailcomsaturday': 3, 'judicial': 3, 'noted': 3, 'old': 3, 'carry': 3, 'described': 3, 'tue': 3, 'balkan': 3, 'weare': 3, 'burma': 3, 'indication': 3, 'fraud': 3, 'pretty': 3, 'mere': 3, 'require': 3, 'unique': 3, 'played': 3, 'value': 3, 'weakness': 3, 'success': 3, 'individual': 3, 'known': 3, 'corruption': 3, 'defend': 3, 'paid': 3, 'here': 3, 'track': 3, 'tony': 3, 'split': 3, 'hagues': 3, 'conducting': 3, 'london': 3, 'czech': 3, 'attending': 3, 'lunch': 3, 'regard': 3, 'spokesman': 3, 'relation': 3, 'accused': 3, 'smear': 3, 'millscdstategovfriday': 3, 'capricia': 3, 'includes': 3, 'jiloty': 3, 'unfortunately': 3, 'kerry': 3, 'lugar': 3, 'interested': 3, 'printh': 3, 'highfyi': 3, 'remains': 3, 'integrity': 3, 'supportive': 3, 'recognized': 3, 'inherited': 3, 'itwas': 3, 'presence': 3, 'declassify': 3, 'miliband': 3, 'village': 3, 'german': 3, 'replaced': 3, 'concluded': 3, 'pole': 3, 'apologised': 3, 'demanded': 3, 'crime': 3, 'sat': 3, 'view': 3, 'grand': 3, 'epp': 3, 'organisation': 3, 'absolutely': 3, 'respond': 3, 'suggestion': 3, 'shortly': 3, 'remove': 3, 'oas': 3, 'quickly': 3, 'spain': 3, 'trust': 3, 'institution': 3, 'consensus': 3, 'reaching': 3, 'hill': 3, 'thru': 3, 'otr': 3, 'location': 3, 'barnard': 3, 'helping': 3, 'helpful': 3, 'cautious': 3, 'stage': 3, 'franklin': 3, 'aggressive': 3, 'emerging': 3, 'danger': 3, 'expansion': 3, 'compared': 3, 'contribution': 3, 'analysis': 3, 'initial': 3, 'lay': 3, 'experience': 3, 'prevent': 3, 'context': 3, 'beyond': 3, 'protect': 3, 'colombia': 3, 'mutual': 3, 'pressing': 3, 'firm': 3, 'essential': 3, 'nea': 3, 'liked': 3, 'insisted': 3, 'thus': 3, 'tried': 3, 'poor': 3, 'worked': 3, 'aide': 3, 'felt': 3, 'task': 3, 'jim': 3, 'jones': 3, 'ban': 3, 'food': 3, 'saturday': 3, 'confirm': 3, 'printed': 3, 'wdutch': 3, 'camera': 3, 'woodward': 3, 'mp': 3, 'caucus': 3, 'pushed': 3, 'appeal': 3, 'sexual': 3, 'operational': 3, 'capacity': 3, 'haitian': 3, 'am': 3, 'improvement': 3, 'russia': 3, 'reduction': 3, 'superpower': 3, 'impossible': 3, 'negotiating': 3, 'partly': 3, 'worse': 3, 'uk': 3, 'dear': 3, 'figure': 3, 'hrodclintonemailcom': 3, 'cdm': 3, 'cnn': 3, 'pledge': 3, 'western': 3, 'civil': 3, 'perfect': 3, 'longterm': 3, 'saudi': 3, 'extremely': 3, 'prepared': 3, 'island': 3, 'direct': 3, 'coordination': 3, 'died': 3, 'ronnie': 3, 'chairman': 3, 'holding': 3, 'added': 3, 'career': 3, 'businessmr': 3, 'shareholder': 3, 'ultimately': 3, 'moved': 3, 'leading': 3, 'permission': 3, 'satisfied': 3, 'natalegawa': 3, 'ãâ': 3, 'availability': 3, 'video': 3, 'cvc': 3, 'svc': 3, 'face': 3, 'commander': 3, 'pakistani': 3, 'everyone': 3, 'improving': 3, 'amhfw': 3, 'sinn': 3, 'westminster': 3, 'policing': 3, 'hardline': 3, 'deny': 3, 'director': 3, 'focus': 3, 'receives': 3, 'data': 3, 'tim': 3, 'pawlenty': 3, 'mississippi': 3, 'ohio': 3, 'okna': 3, 'turning': 3, 'thedemocrat': 3, 'confavorable': 3, 'cathfavorable':

In [253]:
# --- 2. Filter and count words for SPAM (Fraudulent Messages) ---

# Grab all text where the label is 1 (spam) and join it into one giant string
spam_text = " ".join(data[data['label'] == 1]['preprocessed_text'].astype(str))

# Split that giant string into individual words
spam_words = spam_text.split()

# Count the frequencies of each word
spam_word_counts = Counter(spam_words)
print(spam_word_counts)

Counter({'money': 920, 'account': 793, 'bank': 744, 'fund': 702, 'u': 549, 'business': 471, 'transaction': 412, 'country': 404, 'transfer': 392, 'million': 385, 'company': 363, 'foreign': 351, 'contact': 325, 'want': 312, 'next': 309, 'sum': 292, 'dollar': 283, 'know': 281, 'name': 274, 'one': 271, 'kin': 271, 'claim': 255, 'email': 251, 'also': 251, 'mr': 250, 'security': 245, 'family': 242, 'please': 242, 'late': 230, 'government': 229, 'father': 228, 'information': 224, 'since': 223, 'year': 214, 'assistance': 206, 'state': 203, 'died': 203, 'united': 201, 'number': 195, 'come': 194, 'investment': 194, 'may': 193, 'deposit': 192, 'private': 190, 'shall': 188, 'husband': 176, 'address': 174, 'assist': 173, 'decided': 171, 'need': 171, 'would': 170, 'foreigner': 168, 'africa': 166, 'hundred': 166, 'death': 165, 'five': 163, 'contract': 159, 'made': 158, 'fax': 157, 'help': 157, 'receive': 154, 'total': 151, 'document': 151, 'make': 149, 'amount': 148, 'reply': 148, 'trust': 147, 'deposited': 146, 'south': 142, 'get': 142, 'deceased': 141, 'beneficiary': 141, 'god': 141, 'thousand': 137, 'partner': 136, 'proposal': 133, 'person': 133, 'forward': 131, 'payment': 131, 'give': 131, 'de': 128, 'telephone': 126, 'dear': 124, 'soon': 123, 'send': 122, 'work': 121, 'provide': 121, 'immediately': 120, 'interest': 117, 'urgent': 117, 'got': 116, 'letter': 115, 'share': 115, 'time': 115, 'use': 114, 'good': 114, 'risk': 113, 'without': 113, 'new': 111, 'confidential': 110, 'day': 110, 'president': 109, 'dont': 109, 'official': 108, 'enable': 106, 'mail': 106, 'due': 106, 'safe': 105, 'son': 105, 'two': 104, 'present': 104, 'discovered': 103, 'like': 103, 'well': 103, 'reliable': 102, 'life': 101, 'client': 101, 'let': 101, 'invest': 99, 'take': 99, 'first': 98, 'arrangement': 98, 'department': 97, 'service': 97, 'detail': 97, 'personal': 97, 'deal': 96, 'hope': 95, 'necessary': 94, 'back': 94, 'response': 92, 'upon': 91, 'regard': 91, 'nigeria': 91, 'free': 90, 'banking': 88, 'expense': 87, 'wife': 86, 'cooperation': 85, 'interested': 85, 'cannot': 84, 'hear': 84, 'set': 83, 'position': 83, 'crash': 81, 'full': 81, 'project': 81, 'law': 81, 'seek': 80, 'used': 80, 'release': 79, 'owner': 79, 'still': 79, 'must': 78, 'oil': 78, 'within': 78, 'mother': 77, 'going': 77, 'party': 76, 'go': 76, 'contacting': 76, 'sent': 75, 'firm': 74, 'child': 73, 'hence': 73, 'relative': 72, 'successful': 72, 'involved': 72, 'member': 71, 'matter': 71, 'financial': 71, 'attorney': 70, 'wish': 69, 'box': 69, 'manager': 68, 'last': 68, 'whole': 68, 'willing': 68, 'said': 67, 'director': 67, 'call': 67, 'relation': 67, 'transferred': 67, 'part': 66, 'executed': 66, 'office': 66, 'customer': 65, 'put': 65, 'colleague': 65, 'presently': 65, 'nobody': 65, 'phone': 65, 'therefore': 65, 'huge': 65, 'international': 64, 'plane': 64, 'way': 64, 'confidence': 64, 'reason': 64, 'end': 63, 'fact': 63, 'twenty': 63, 'look': 62, 'utmost': 62, 'national': 62, 'message': 62, 'former': 62, 'opportunity': 61, 'came': 61, 'finance': 61, 'consignment': 61, 'best': 61, 'keep': 61, 'request': 61, 'via': 61, 'confidentiality': 61, 'believe': 61, 'percentage': 61, 'unclaimed': 58, 'following': 58, 'left': 57, 'usd': 57, 'people': 57, 'working': 56, 'place': 56, 'order': 56, 'dr': 56, 'th': 56, 'war': 56, 'either': 56, 'never': 56, 'along': 55, 'search': 55, 'could': 55, 'civil': 55, 'situation': 55, 'political': 55, 'investigation': 54, 'stand': 54, 'kindly': 53, 'contractor': 53, 'immediate': 53, 'property': 52, 'ministry': 52, 'behalf': 52, 'handle': 52, 'course': 51, 'note': 51, 'paid': 51, 'aside': 51, 'charge': 51, 'la': 51, 'agreed': 50, 'intend': 50, 'meet': 50, 'based': 50, 'receipt': 50, 'move': 50, 'able': 50, 'world': 50, 'purpose': 50, 'require': 49, 'month': 49, 'required': 49, 'honest': 49, 'four': 49, 'officer': 49, 'legal': 49, 'management': 49, 'youe': 49, 'seeking': 48, 'according': 48, 'great': 48, 'benefit': 48, 'including': 48, 'head': 48, 'ask': 47, 'treasury': 47, 'urgently': 47, 'result': 47, 'needed': 47, 'communication': 47, 'abroad': 47, 'modality': 47, 'petroleum': 47, 'le': 47, 'cash': 47, 'nature': 46, 'done': 46, 'farmer': 46, 'old': 46, 'understand': 46, 'friend': 46, 'leaving': 46, 'given': 46, 'approval': 45, 'surprise': 45, 'offer': 45, 'federal': 45, 'african': 45, 'process': 45, 'balance': 45, 'rest': 45, 'discus': 45, 'mutual': 45, 'receiving': 44, 'inform': 44, 'respect': 44, 'form': 44, 'capital': 44, 'development': 44, 'europe': 44, 'ready': 44, 'however': 44, 'land': 44, 'bill': 43, 'might': 43, 'profitable': 43, 'write': 43, 'thing': 43, 'six': 43, 'right': 43, 'told': 43, 'secret': 42, 'live': 42, 'abidjan': 42, 'secure': 42, 'highly': 42, 'important': 42, 'corporation': 42, 'mre': 42, 'local': 41, 'problem': 41, 'top': 41, 'line': 41, 'youi': 41, 'treat': 41, 'west': 41, 'et': 41, 'approved': 41, 'currently': 41, 'vous': 41, 'republic': 40, 'direct': 40, 'easy': 40, 'subsequent': 40, 'branch': 40, 'reach': 40, 'making': 40, 'face': 40, 'zimbabwe': 40, 'sharing': 39, 'see': 39, 'found': 39, 'internet': 39, 'though': 39, 'assurance': 39, 'find': 39, 'assure': 39, 'venture': 39, 'valued': 39, 'nigerian': 39, 'act': 39, 'indicated': 38, 'file': 38, 'agreement': 38, 'await': 38, 'real': 38, 'contacted': 38, 'sure': 38, 'cote': 38, 'medium': 38, 'solicit': 38, 'support': 37, 'trustworthy': 37, 'transfered': 37, 'behind': 37, 'plan': 37, 'conclusion': 37, 'que': 37, 'entire': 36, 'indicate': 36, 'possible': 36, 'future': 36, 'estate': 36, 'accept': 35, 'custody': 35, 'pay': 35, 'seven': 35, 'rebel': 35, 'thirty': 35, 'kept': 34, 'safety': 34, 'disbursement': 34, 'apply': 34, 'execution': 34, 'much': 34, 'white': 34, 'overseas': 34, 'around': 34, 'auditing': 34, 'later': 34, 'concerning': 34, 'three': 34, 'writing': 33, 'applies': 33, 'every': 33, 'remaining': 33, 'care': 33, 'hospital': 33, 'area': 33, 'took': 33, 'introduce': 33, 'read': 33, 'asylum': 33, 'several': 33, 'open': 33, 'farm': 33, 'stated': 32, 'trace': 32, 'aware': 32, 'killed': 32, 'capable': 32, 'house': 32, 'chief': 32, 'start': 32, 'en': 32, 'incurred': 31, 'discovery': 31, 'application': 31, 'ago': 31, 'hand': 31, 'authority': 31, 'home': 31, 'bless': 31, 'lawyer': 31, 'operation': 31, 'moved': 31, 'partnership': 31, 'source': 31, 'exchange': 30, 'abandoned': 30, 'man': 30, 'pending': 30, 'finally': 30, 'feel': 30, 'lost': 30, 'code': 30, 'operate': 30, 'special': 30, 'permit': 30, 'taking': 30, 'protect': 30, 'worked': 30, 'power': 30, 'je': 30, 'remittance': 29, 'usm': 29, 'assured': 29, 'record': 29, 'long': 29, 'notice': 29, 'action': 29, 'paperwork': 29, 'sending': 29, 'side': 29, 'charles': 29, 'view': 29, 'general': 29, 'married': 29, 'always': 29, 'charity': 29, 'unless': 28, 'ever': 28, 'effort': 28, 'instruction': 28, 'award': 28, 'lot': 28, 'received': 28, 'refugee': 28, 'individual': 28, 'taylor': 28, 'choice': 28, 'locate': 28, 'include': 28, 'advice': 28, 'american': 28, 'dormant': 28, 'al': 28, 'diamond': 28, 'strictly': 27, 'unfortunately': 27, 'transactione': 27, 'acceptance': 27, 'level': 27, 'committee': 27, 'fear': 27, 'attempt': 27, 'leave': 27, 'guarantee': 27, 'un': 27, 'remit': 27, 'secretly': 27, 'favour': 27, 'investing': 27, 'confiscated': 27, 'anything': 27, 'outside': 27, 'gold': 26, 'relationship': 26, 'ownership': 26, 'yahoo': 26, 'provided': 26, 'secured': 26, 'aid': 26, 'known': 26, 'even': 26, 'liberia': 26, 'second': 26, 'percent': 26, 'mean': 26, 'fixed': 26, 'keeping': 26, 'ac': 26, 'carry': 25, 'return': 25, 'thanks': 25, 'supply': 25, 'another': 25, 'knowledge': 25, 'coming': 25, 'high': 25, 'chairman': 25, 'miss': 25, 'kind': 25, 'legitimate': 25, 'secrecy': 25, 'ten': 25, 'furnish': 25, 'looking': 25, 'major': 25, 'central': 25, 'content': 25, 'ivory': 25, 'rich': 25, 'belongs': 24, 'expecting': 24, 'nation': 24, 'genuine': 24, 'agree': 24, 'declare': 24, 'prepare': 24, 'period': 24, 'original': 24, 'consent': 24, 'everything': 24, 'merchant': 24, 'peace': 24, 'certificate': 24, 'reputable': 24, 'avoid': 24, 'allow': 24, 'willingness': 24, 'transferring': 24, 'confirm': 24, 'change': 24, 'coast': 24, 'minister': 24, 'condition': 24, 'organization': 24, 'serve': 23, 'countrye': 23, 'already': 23, 'documentation': 23, 'relevant': 23, 'many': 23, 'nine': 23, 'iraq': 23, 'youc': 23, 'called': 23, 'positive': 23, 'attention': 23, 'concluded': 23, 'case': 23, 'desire': 23, 'health': 23, 'believing': 23, 'fifty': 23, 'ãââ½': 23, 'guideline': 22, 'managing': 22, 'arrival': 22, 'helping': 22, 'using': 22, 'mining': 22, 'daughter': 22, 'actually': 22, 'sincerely': 22, 'unsuccessful': 22, 'prime': 22, 'thistransaction': 22, 'smooth': 22, 'released': 22, 'quite': 22, 'entitled': 22, 'till': 22, 'june': 22, 'accounting': 22, 'different': 22, 'recently': 22, 'eight': 22, 'netherlands': 22, 'sierra': 22, 'someone': 21, 'ratio': 21, 'complete': 21, 'advise': 21, 'visit': 21, 'fail': 21, 'ofthe': 21, 'floating': 21, 'searching': 21, 'cocoa': 21, 'divoire': 21, 'lucrative': 21, 'belonging': 21, 'really': 21, 'accountant': 21, 'reposed': 21, 'informed': 21, 'value': 21, 'st': 21, 'across': 21, 'joint': 21, 'proved': 21, 'declared': 21, 'issued': 21, 'remitted': 21, 'credit': 21, 'proposition': 21, 'self': 21, 'group': 21, 'taken': 21, 'burkina': 21, 'mugabe': 21, 'diplomatic': 21, 'facedarial': 21, 'mind': 20, 'effect': 20, 'bring': 20, 'expect': 20, 'conclude': 20, 'success': 20, 'past': 20, 'question': 20, 'copy': 20, 'representative': 20, 'strong': 20, 'point': 20, 'decision': 20, 'allah': 20, 'sign': 20, 'crisis': 20, 'black': 20, 'involve': 20, 'asset': 20, 'sale': 20, 'routine': 20, 'review': 20, 'servant': 20, 'list': 20, 'accounti': 20, 'close': 20, 'ensure': 20, 'london': 20, 'ce': 20, 'hariri': 20, 'sir': 19, 'dakar': 19, 'senegal': 19, 'less': 19, 'commercial': 19, 'properly': 19, 'awarded': 19, 'together': 19, 'military': 19, 'getting': 19, 'actual': 19, 'cost': 19, 'october': 19, 'tell': 19, 'messenger': 19, 'usmillion': 19, 'treasure': 19, 'product': 19, 'barrister': 19, 'sincere': 19, 'notification': 19, 'officially': 19, 'waiting': 19, 'beneficial': 19, 'allowed': 19, 'vital': 19, 'twelve': 19, 'iraqi': 19, 'public': 19, 'force': 19, 'pray': 19, 'leone': 19, 'led': 19, 'pound': 19, 'divfont': 19, 'resource': 18, 'board': 18, 'wealth': 18, 'worthy': 18, 'trade': 18, 'conduct': 18, 'associate': 18, 'chamber': 18, 'industry': 18, 'purchase': 18, 'alone': 18, 'step': 18, 'johannesburg': 18, 'lived': 18, 'become': 18, 'idea': 18, 'hearing': 18, 'oilfield': 18, 'proceeds': 18, 'breach': 18, 'trusted': 18, 'abacha': 18, 'proceed': 18, 'online': 18, 'considering': 18, 'date': 18, 'christian': 18, 'approve': 18, 'robert': 18, 'div': 18, 'whose': 18, 'managed': 17, 'nominated': 17, 'text': 17, 'compensation': 17, 'expiration': 17, 'trip': 17, 'week': 17, 'locating': 17, 'big': 17, 'magnitude': 17, 'lord': 17, 'procedure': 17, 'met': 17, 'glad': 17, 'towards': 17, 'divnbspdiv': 17, 'respond': 17, 'staff': 17, 'flight': 17, 'extended': 17, 'transactionc': 17, 'auditor': 17, 'faso': 17, 'section': 17, 'moneye': 17, 'advised': 17, 'correct': 17, 'du': 17, 'calendar': 17, 'maturity': 17, 'recent': 17, 'personally': 17, 'valuable': 17, 'better': 17, 'zimbabwean': 17, 'widthd': 17, 'nextofkin': 16, 'commence': 16, 'prompt': 16, 'possession': 16, 'nothing': 16, 'remain': 16, 'equipment': 16, 'instruct': 16, 'revert': 16, 'ghana': 16, 'observe': 16, 'usa': 16, 'july': 16, 'pleasure': 16, 'gave': 16, 'soul': 16, 'establish': 16, 'far': 16, 'access': 16, 'propose': 16, 'economic': 16, 'education': 16, 'williams': 16, 'option': 16, 'website': 16, 'understanding': 16, 'status': 16, 'agent': 16, 'killing': 16, 'civilian': 16, 'nominate': 16, 'urgency': 16, 'kingdom': 16, 'cancer': 16, 'destroy': 16, 'demand': 16, 'votre': 16, 'away': 16, 'opened': 16, 'ahmed': 16, 'influence': 16, 'least': 16, 'carefully': 16, 'control': 16, 'portfolio': 16, 'alive': 16, 'doctor': 16, 'heart': 16, 'medical': 16, 'february': 16, 'dans': 16, 'pour': 16, 'november': 15, 'mandated': 15, 'particular': 15, 'save': 15, 'hr': 15, 'today': 15, 'somebody': 15, 'stipulates': 15, 'ouagadougou': 15, 'issue': 15, 'acknowledge': 15, 'endeavor': 15, 'forwarding': 15, 'mapped': 15, 'assisting': 15, 'acceptable': 15, 'enquiry': 15, 'brief': 15, 'co': 15, 'internal': 15, 'tax': 15, 'america': 15, 'monitoring': 15, 'directive': 15, 'absolute': 15, 'thank': 15, 'invoiced': 15, 'legally': 15, 'dead': 15, 'smith': 15, 'notify': 15, 'regardsc': 15, 'operated': 15, 'chance': 15, 'correspondence': 15, 'commission': 15, 'fly': 15, 'nasser': 15, 'shared': 15, 'philippine': 15, 'donate': 15, 'murdered': 15, 'chemical': 15, 'adam': 15, 'stay': 15, 'ibrahim': 15, 'rafik': 15, 'cellpaddingd': 15, 'fifteen': 14, 'billion': 14, 'serious': 14, 'secretary': 14, 'capability': 14, 'among': 14, 'supposed': 14, 'remained': 14, 'communicate': 14, 'soliciting': 14, 'available': 14, 'subject': 14, 'discussed': 14, 'anticipation': 14, 'commerce': 14, 'execute': 14, 'proper': 14, 'russian': 14, 'ltd': 14, 'discussion': 14, 'attached': 14, 'embassy': 14, 'various': 14, 'successfully': 14, 'british': 14, 'numbered': 14, 'coded': 14, 'france': 14, 'knowing': 14, 'betray': 14, 'named': 14, 'intended': 14, 'say': 14, 'forfeited': 14, 'valid': 14, 'themoney': 14, 'peter': 14, 'placed': 14, 'directly': 14, 'paul': 14, 'worth': 14, 'paper': 14, 'johnson': 14, 'current': 14, 'cellspacingd': 14, 'heir': 13, 'completion': 13, 'machinery': 13, 'dre': 13, 'arrange': 13, 'natural': 13, 'export': 13, 'started': 13, 'entertain': 13, 'uk': 13, 'mobile': 13, 'affidavit': 13, 'facilitate': 13, 'final': 13, 'occasioned': 13, 'true': 13, 'wait': 13, 'sorry': 13, 'brother': 13, 'explain': 13, 'david': 13, 'benin': 13, 'passport': 13, 'arm': 13, 'george': 13, 'previously': 13, 'profile': 13, 'angola': 13, 'directory': 13, 'awaiting': 13, 'air': 13, 'msn': 13, 'herein': 13, 'millionc': 13, 'uscce': 13, 'willbe': 13, 'role': 13, 'swiss': 13, 'repose': 13, 'city': 13, 'privileged': 13, 'anyone': 13, 'remains': 13, 'maintain': 13, 'desk': 13, 'forty': 13, 'john': 13, 'intact': 13, 'presence': 13, 'assuring': 13, 'anybody': 13, 'blessed': 13, 'trunk': 13, 'choose': 13, 'sister': 13, 'sterling': 13, 'colordblack': 13, 'neither': 12, 'maintained': 12, 'returned': 12, 'appropriate': 12, 'saddled': 12, 'giving': 12, 'engr': 12, 'reserve': 12, 'enough': 12, 'detailed': 12, 'incidental': 12, 'delay': 12, 'hassan': 12, 'appreciate': 12, 'indicating': 12, 'prize': 12, 'democratic': 12, 'word': 12, 'eventually': 12, 'containing': 12, 'existing': 12, 'ofthis': 12, 'faithfully': 12, 'uncle': 12, 'cause': 12, 'resident': 12, 'lay': 12, 'body': 12, 'type': 12, 'assistancee': 12, 'main': 12, 'largest': 12, 'bureau': 12, 'material': 12, 'regarding': 12, 'unserviceable': 12, 'whether': 12, 'profession': 12, 'construction': 12, 'affair': 12, 'january': 12, 'reminder': 12, 'morris': 12, 'passenger': 12, 'disclose': 12, 'intention': 12, 'hoping': 12, 'airline': 12, 'investor': 12, 'executive': 12, 'accounte': 12, 'accord': 12, 'countryc': 12, 'treated': 12, 'bonafide': 12, 'verification': 12, 'gratification': 12, 'retire': 12, 'widow': 12, 'buy': 12, 'friendi': 12, 'seized': 12, 'audit': 12, 'holder': 12, 'rather': 12, 'truth': 12, 'millionfive': 12, 'physical': 12, 'avec': 12, 'duty': 12, 'thismoney': 12, 'program': 12, 'non': 12, 'leader': 12, 'ali': 12, 'staying': 12, 'asked': 12, 'inherited': 12, 'resulted': 12, 'thailand': 12, 'policy': 12, 'treatment': 12, 'lebanese': 12, 'mon': 12, 'computer': 12, 'hereby': 12, 'outstanding': 12, 'attack': 12, 'une': 12, 'bgcolordwhite': 12, 'borderdtbodytr': 12, 'valigndtoptd': 12, 'sizedtable': 12, 'classdrtefont': 12, 'otherwise': 11, 'designated': 11, 'companye': 11, 'cover': 11, 'key': 11, 'meanwhile': 11, 'effective': 11, 'location': 11, 'compensate': 11, 'accident': 11, 'principal': 11, 'william': 11, 'refinery': 11, 'series': 11, 'learnt': 11, 'prove': 11, 'sierraleone': 11, 'untimely': 11, 'handed': 11, 'young': 11, 'offshore': 11, 'miscellaneous': 11, 'age': 11, 'consider': 11, 'asking': 11, 'seeker': 11, 'else': 11, 'mutually': 11, 'factory': 11, 'expected': 11, 'early': 11, 'sirmadam': 11, 'particularly': 11, 'processed': 11, 'inthe': 11, 'youei': 11, 'opening': 11, 'forthe': 11, 'arise': 11, 'escaped': 11, 'southern': 11, 'identity': 11, 'permission': 11, 'news': 11, 'especially': 11, 'faithfullydr': 11, 'passed': 11, 'suggestion': 11, 'incure': 11, 'onward': 11, 'clearance': 11, 'advance': 11, 'trouble': 11, 'continue': 11, 'research': 11, 'involvement': 11, 'trial': 11, 'follow': 11, 'liberian': 11, 'acquire': 11, 'sani': 11, 'danger': 11, 'viable': 11, 'veteran': 11, 'illegal': 11, 'became': 11, 'lodged': 11, 'held': 11, 'regret': 11, 'center': 11, 'somme': 11, 'nous': 11, 'widthdfont': 11, 'thus': 10, 'siri': 10, 'frozen': 10, 'moore': 10, 'birth': 10, 'urge': 10, 'touch': 10, 'moment': 10, 'obtain': 10, 'arranged': 10, 'meant': 10, 'instructed': 10, 'joseph': 10, 'expert': 10, 'front': 10, 'gotten': 10, 'disappoint': 10, 'almighty': 10, 'poisoned': 10, 'funde': 10, 'honourably': 10, 'senior': 10, 'adviser': 10, 'saw': 10, 'beloved': 10, 'lagos': 10, 'responsibility': 10, 'citizen': 10, 'ton': 10, 'yuan': 10, 'pipe': 10, 'administration': 10, 'crashed': 10, 'shell': 10, 'april': 10, 'car': 10, 'job': 10, 'engineer': 10, 'collect': 10, 'mrse': 10, 'mee': 10, 'owned': 10, 'nnpc': 10, 'empty': 10, 'korea': 10, 'living': 10, 'run': 10, 'involves': 10, 'operating': 10, 'external': 10, 'satisfaction': 10, 'banker': 10, 'raise': 10, 'eye': 10, 'clarification': 10, 'adviced': 10, 'european': 10, 'stock': 10, 'survival': 10, 'webmail': 10, 'site': 10, 'banke': 10, 'crave': 10, 'regarded': 10, 'burkinafaso': 10, 'sirc': 10, 'residing': 10, 'andthe': 10, 'accused': 10, 'excess': 10, 'alhaji': 10, 'fofanah': 10, 'ahead': 10, 'pleasec': 10, 'travel': 10, 'contained': 10, 'vehicle': 10, 'el': 10, 'guide': 10, 'indulgence': 10, 'implore': 10, 'reform': 10, 'oversea': 10, 'courier': 10, 'art': 10, 'il': 10, 'import': 9, 'mine': 9, 'personality': 9, 'mentioned': 9, 'usc': 9, 'alternative': 9, 'food': 9, 'item': 9, 'produce': 9, 'submit': 9, 'registered': 9, 'atom': 9, 'industrialist': 9, 'compliment': 9, 'consequently': 9, 'sector': 9, 'alongside': 9, 'lawrence': 9, 'wanted': 9, 'knew': 9, 'kabila': 9, 'check': 9, 'handicapped': 9, 'active': 9, 'yr': 9, 'wealthy': 9, 'lead': 9, 'surprised': 9, 'net': 9, 'gone': 9, 'voice': 9, 'securitycompany': 9, 'prepared': 9, 'inherit': 9, 'afraid': 9, 'advantage': 9, 'think': 9, 'repatriating': 9, 'confidentialitye': 9, 'previous': 9, 'bid': 9, 'settle': 9, 'york': 9, 'consultantcontractor': 9, 'humble': 9, 'network': 9, 'parent': 9, 'unitedstates': 9, 'consequentlyc': 9, 'prohibited': 9, 'sumc': 9, 'deserves': 9, 'career': 9, 'expedite': 9, 'quarter': 9, 'yeare': 9, 'anticipated': 9, 'relayed': 9, 'brow': 9, 'fellow': 9, 'picture': 9, 'except': 9, 'experience': 9, 'consultant': 9, 'confiscate': 9, 'reward': 9, 'james': 9, 'statesdollars': 9, 'binding': 9, 'convinced': 9, 'endeavour': 9, 'dubai': 9, 'chevron': 9, 'happen': 9, 'tried': 9, 'employer': 9, 'terrorism': 9, 'institute': 9, 'certain': 9, 'dealing': 9, 'regime': 9, 'born': 9, 'estrada': 9, 'movement': 9, 'illness': 9, 'confidentiallity': 9, 'processing': 9, 'recieve': 9, 'union': 9, 'lying': 9, 'ihave': 9, 'blood': 9, 'dispute': 9, 'try': 9, 'men': 9, 'relocate': 9, 'courage': 9, 'virtue': 9, 'cbn': 9, 'centre': 9, 'carrying': 9, 'bind': 9, 'meeting': 9, 'task': 9, 'vault': 9, 'providing': 9, 'accountc': 9, 'render': 9, 'comme': 9, 'coleman': 9, 'maria': 9, 'colis': 9, 'heard': 8, 'agricultural': 8, 'totally': 8, 'securing': 8, 'foriegn': 8, 'tender': 8, 'importation': 8, 'provision': 8, 'im': 8, 'poor': 8, 'kelly': 8, 'bos': 8, 'hitch': 8, 'disclosed': 8, 'single': 8, 'hesitate': 8, 'assistant': 8, 'congo': 8, 'overdue': 8, 'totaling': 8, 'importance': 8, 'privilege': 8, 'meimmediately': 8, 'residential': 8, 'army':

In [254]:
print(data_train.columns)

Index(['text', 'label', 'preprocessed_text'], dtype='str')

## Extra features

In [255]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,preprocessed_text,money_mark,suspicious_words,text_len
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",1,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",0,0,106
535,I have not been able to reach oscar this am. W...,0,I have not been able to reach oscar this am. W...,0,0,101
695,; Huma Abedin B6I'm checking with Pat on the 5...,0,; Huma Abedin B6I'm checking with Pat on the 5...,0,0,141
557,I can have it announced here on Monday - can't...,0,I can have it announced here on Monday - can't...,0,0,52
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,1,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,0,1,1750

## How would work the Bag of Words with Count Vectorizer concept?

In [256]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the vectorizer

# lowercase=True and stop_words='english' to clean up text automatically!
vectorizer = CountVectorizer(lowercase=True, stop_words='english')

#Teaching the vectorizer  vocabulary and transform the text column into numbers
X_train_bow = vectorizer.fit_transform(data_train['text'])

# Transform the validation data
X_val_bow = vectorizer.transform(data_val['text'])

# print matrix 
bow_df = pd.DataFrame(X_train_bow.toarray(), columns=vectorizer.get_feature_names_out())
bow_df.head()

,00,000,000000,00000e25,00000e251,00000eur,000066,0000ff,000m,000million,...,â½s,â½t,â½ta,â½te,â½tica,â½to,â½trangers,â½x60ã,â½x70,â½ã
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [257]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

# Load the vectorizer 
stop_words_list = list(stopwords.words('english'))
tfidf_vectorizer = TfidfVectorizer(lowercase=True, stop_words=stop_words_list)

In [258]:
#Vectorize the dataset (Fit and transform train text, only transform validation text)
X_train_tfidf = tfidf_vectorizer.fit_transform(data_train['text'])
X_val_tfidf = tfidf_vectorizer.transform(data_val['text'])

In [259]:
# Print the shape of the vectorized dataset
print("Shape of Training Vectorized Dataset:", X_train_tfidf.shape)
print("Shape of Validation Vectorized Dataset:", X_val_tfidf.shape)

Shape of Training Vectorized Dataset: (800, 23238)
Shape of Validation Vectorized Dataset: (200, 23238)

## And the Train a Classifier?

In [260]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [261]:
# target labels 
y_train = data_train['label']
y_val = data_val['label']

In [262]:
#Initialize the classifier (Using Naive Bayes)
classifier = MultinomialNB()

In [263]:
# Train the model using your training vectors and training labels
classifier.fit(X_train_tfidf, y_train)

MultinomialNB()

In [264]:
#Predict classifications on the validation dataset
y_pred = classifier.predict(X_val_tfidf)

In [265]:
# EVALUATE PERFORMANCE
print(f"Validation Accuracy: {accuracy_score(y_val, y_pred) * 100:.2f}%\n")
print("Detailed Classification Report:")
print(classification_report(y_val, y_pred))

Validation Accuracy: 95.00%

Detailed Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.92      0.96       125
           1       0.88      1.00      0.94        75

    accuracy                           0.95       200
   macro avg       0.94      0.96      0.95       200
weighted avg       0.96      0.95      0.95       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [269]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from scipy.sparse import hstack, csr_matrix

In [270]:
# =========================================================================
# 0. PREPARE THE DATA & EXTRA FEATURES
# =========================================================================
# Extract target labels
y_train = data_train['label']
y_val = data_val['label']

# Create dense arrays for your 3 engineered features
# We wrap them in csr_matrix to make them compatible with sparse vectorizer outputs
extra_features_train = csr_matrix(data_train[['money_mark', 'suspicious_words', 'text_len']].values)
extra_features_val = csr_matrix(data_val[['money_mark', 'suspicious_words', 'text_len']].values)

In [271]:
# =========================================================================
# EXPERIMENT 1: Bag of Words Only
# =========================================================================
bow_vectorizer = CountVectorizer()
X_train_exp1 = bow_vectorizer.fit_transform(data_train['preprocessed_text'])
X_val_exp1 = bow_vectorizer.transform(data_val['preprocessed_text'])

model_exp1 = MultinomialNB() # Default parameters
model_exp1.fit(X_train_exp1, y_train)
acc_exp1 = accuracy_score(y_val, model_exp1.predict(X_val_exp1))

In [272]:
# =========================================================================
# EXPERIMENT 2: TF-IDF Only
# =========================================================================
tfidf_vectorizer = TfidfVectorizer()
X_train_exp2 = tfidf_vectorizer.fit_transform(data_train['preprocessed_text'])
X_val_exp2 = tfidf_vectorizer.transform(data_val['preprocessed_text'])

model_exp2 = MultinomialNB() # Default parameters
model_exp2.fit(X_train_exp2, y_train)
acc_exp2 = accuracy_score(y_val, model_exp2.predict(X_val_exp2))

In [273]:
# =========================================================================
# EXPERIMENT 3: Bag of Words + Extra Flags
# =========================================================================
# Horizontally stack the BoW matrix with our 3 numerical feature columns
X_train_exp3 = hstack([X_train_exp1, extra_features_train])
X_val_exp3 = hstack([X_val_exp1, extra_features_val])

model_exp3 = MultinomialNB() # Default parameters
model_exp3.fit(X_train_exp3, y_train)
acc_exp3 = accuracy_score(y_val, model_exp3.predict(X_val_exp3))

In [275]:
# =========================================================================
# EXPERIMENT 4: TF-IDF + Extra Flags
# =========================================================================
# Horizontally stack the TF-IDF matrix with our 3 numerical feature columns
X_train_exp4 = hstack([X_train_exp2, extra_features_train])
X_val_exp4 = hstack([X_val_exp2, extra_features_val])

model_exp4 = MultinomialNB() # Default parameters
model_exp4.fit(X_train_exp4, y_train)
acc_exp4 = accuracy_score(y_val, model_exp4.predict(X_val_exp4))

In [276]:
# =========================================================================
# VISUALIZE THE BENCHMARK RESULTS
# =========================================================================
results_df = pd.DataFrame({
    'Feature Configuration': [
        '1. Bag of Words Only', 
        '2. TF-IDF Only', 
        '3. Bag of Words + Extra Flags', 
        '4. TF-IDF + Extra Flags'
    ],
    'Validation Accuracy': [acc_exp1, acc_exp2, acc_exp3, acc_exp4]
})

# Convert to clean percentages
results_df['Validation Accuracy'] = results_df['Validation Accuracy'].map(lambda x: f"{x*100:.2f}%")
display(results_df)

           Feature Configuration Validation Accuracy
0           1. Bag of Words Only              92.00%
1                 2. TF-IDF Only              86.00%
2  3. Bag of Words + Extra Flags              81.00%
3        4. TF-IDF + Extra Flags              57.00%